assetic:
    bundles:
        - 'BigfootAceThemeBundle'
    assets:
        admin_jquery:
            inputs:
                - 'bundles/bigfootacetheme/vendor/jquery/dist/jquery.min.js'
        admin_js:
            inputs:
                - 'bundles/bigfootacetheme/js/bootstrap.min.js'
                - 'bundles/bigfootacetheme/js/bootbox.min.js'
                - 'bundles/bigfootacetheme/js/dropzone.min.js'
                - 'bundles/bigfootacetheme/js/typeahead-bs2.min.js'
                - 'bundles/bigfootacetheme/js/jquery-ui-1.10.3.full.min.js'
                - 'bundles/bigfootacetheme/js/jquery.ui.touch-punch.min.js'
                - 'bundles/bigfootacetheme/js/chosen.jquery.min.js'
                - 'bundles/bigfootacetheme/js/fuelux/fuelux.spinner.min.js'
                - 'bundles/bigfootacetheme/js/date-time/bootstrap-datepicker.min.js'
                - 'bundles/bigfootacetheme/js/date-time/bootstrap-timepicker.min.js'
                - 'bundles/bigfootacetheme/js/date-time/moment.min.js'
                - 'bundles/bigfootacetheme/js/date-time/daterangepicker.min.js'
                - 'bundles/bigfootacetheme/js/bootstrap-colorpicker.min.js'
                - 'bundles/bigfootacetheme/js/jquery.knob.min.js'
                - 'bundles/bigfootacetheme/js/jquery.autosize.min.js'
                - 'bundles/bigfootacetheme/js/jquery.inputlimiter.1.3.1.min.js'
                - 'bundles/bigfootacetheme/js/jquery.maskedinput.min.js'
                - 'bundles/bigfootacetheme/js/bootstrap-tag.min.js'
                - 'bundles/bigfootacetheme/js/bootstrap-wysiwyg.min.js'
                - 'bundles/bigfootacetheme/js/ace-elements.min.js'
                - 'bundles/bigfootacetheme/js/ace.min.js'
                - 'bundles/bigfootacetheme/js/custom.js'
                - 'bundles/bigfootacetheme/js/jquery.portfolio.js'
                - 'bundles/bigfootacetheme/js/jquery.colorbox-min.js'
                - 'bundles/bigfootacetheme/js/jquery.gritter.min.js'
                - 'bundles/bigfootacetheme/js/spin.min.js'
                - 'bundles/bigfootacetheme/js/jqGrid/jquery.jqGrid.min.js'
                - 'bundles/bigfootacetheme/js/jqGrid/custom.js'
                - 'bundles/bigfootacetheme/js/jquery.carouFredSel.js'
                - 'bundles/bigfootacetheme/vendor/ckeditor/ckeditor.js'
                - '%kernel.root_dir%/../vendor/jms/twig-js/twig.js'
            vars:
                - 'locale'
        admin_css:
            inputs:
               - 'bundles/bigfootacetheme/css/bootstrap.min.css'
               - 'bundles/bigfootacetheme/css/font-awesome.min.css'
               - 'bundles/bigfootacetheme/css/jquery-ui-1.10.3.full.min.css'
               - 'bundles/bigfootacetheme/css/jquery-ui-1.10.3.custom.min.css'
               - 'bundles/bigfootacetheme/css/chosen.css'
               - 'bundles/bigfootacetheme/css/datepicker.css'
               - 'bundles/bigfootacetheme/css/bootstrap-timepicker.css'
               - 'bundles/bigfootacetheme/css/daterangepicker.css'
               - 'bundles/bigfootacetheme/css/colorpicker.css'
               - 'bundles/bigfootacetheme/css/ace-fonts.css'
               - 'bundles/bigfootacetheme/css/ui.jqgrid.css'
               - 'bundles/bigfootacetheme/css/ace-fonts.css'
               - 'bundles/bigfootacetheme/css/ace.min.css'
               - 'bundles/bigfootacetheme/css/ace-rtl.min.css'
               - 'bundles/bigfootacetheme/css/ace-skins.min.css'
               - 'bundles/bigfootacetheme/css/jquery.gritter.css'
               - 'bundles/bigfootacetheme/css/colorbox.css'
               - 'bundles/bigfootacetheme/css/custom.css'
            vars:
                - 'locale'
            filters:
                - 'cssrewrite'
        admin_twig_js:
            inputs:
                - '@BigfootAceThemeBundle/Resources/views/modal/confirm.html.twig'
                - '@BigfootAceThemeBundle/Resources/views/modal/base.html.twig'
            filters:
                - 'twig_js'
