assetic:
    bundles:
        - 'BigfootAceThemeBundle'
    assets:
        admin_jquery:
            inputs:
                - 'bundles/bigfootacetheme/vendor/jquery/dist/jquery.min.js'
        admin_js:
            inputs:
                - 'bundles/bigfootacetheme/js/scripts.min.js'
                - '%kernel.root_dir%/../vendor/jms/twig-js/twig.js'
        admin_css:
            inputs:
                - 'bundles/bigfootacetheme/css/styles.min.css'
        admin_twig_js:
            inputs:
                - '@BigfootAceThemeBundle/Resources/views/modal/confirm.html.twig'
                - '@BigfootAceThemeBundle/Resources/views/modal/base.html.twig'
